// Package evm provides a ChainStaker adapter for EVM-compatible chains.
// Contract bindings are generated by abigen and wired in via NewEVMStaker.
package evm

import (
	"context"
	"errors"
	"fmt"
	"math/big"
	"time"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/jhionan/multichain-staking/internal/chain"
	"github.com/jhionan/multichain-staking/internal/chain/evm/bindings"
	"github.com/jhionan/multichain-staking/internal/signer"
	"github.com/rs/zerolog"
)

// ErrContractNotConnected is returned by transaction methods when the adapter
// was constructed without contract bindings (e.g. in read-only or test mode).
var ErrContractNotConnected = errors.New("evm: not connected to contract — abigen bindings not yet integrated")

// ErrUseIndexedDB is returned by ListPositions because position listing is
// handled by the off-chain indexer, not by direct contract reads.
var ErrUseIndexedDB = errors.New("evm: use indexed DB for listing positions")

// hardcodedTiers mirrors the on-chain tier configuration.
// Values must be kept in sync with the deployed contract constants.
var hardcodedTiers = []chain.Tier{
	{
		Type:     chain.TierBronze,
		LockDays: 30,
		APRBps:   500,
		MinStake: big.NewInt(0),
	},
	{
		Type:     chain.TierSilver,
		LockDays: 60,
		APRBps:   1000,
		MinStake: big.NewInt(0),
	},
	{
		Type:     chain.TierGold,
		LockDays: 90,
		APRBps:   1800,
		MinStake: big.NewInt(0),
	},
}

// EVMStaker implements chain.ChainStaker for EVM-compatible chains.
type EVMStaker struct {
	client      *ethclient.Client
	signer      *signer.EVMSigner
	staking     *bindings.TieredStaking
	token       *bindings.StakingToken
	stakingAddr common.Address
	tokenAddr   common.Address
	logger      zerolog.Logger
}

// NewEVMStaker creates an EVMStaker wired to live contract bindings.
// client, stakingAddress, tokenAddress, and signer are all required.
func NewEVMStaker(
	client *ethclient.Client,
	stakingAddress common.Address,
	tokenAddress common.Address,
	sgn *signer.EVMSigner,
	logger zerolog.Logger,
) (*EVMStaker, error) {
	if client == nil {
		return nil, fmt.Errorf("evm: ethclient must not be nil")
	}
	if sgn == nil {
		return nil, fmt.Errorf("evm: signer must not be nil")
	}

	stakingContract, err := bindings.NewTieredStaking(stakingAddress, client)
	if err != nil {
		return nil, fmt.Errorf("evm: failed to bind TieredStaking contract: %w", err)
	}

	tokenContract, err := bindings.NewStakingToken(tokenAddress, client)
	if err != nil {
		return nil, fmt.Errorf("evm: failed to bind StakingToken contract: %w", err)
	}

	return &EVMStaker{
		client:      client,
		signer:      sgn,
		staking:     stakingContract,
		token:       tokenContract,
		stakingAddr: stakingAddress,
		tokenAddr:   tokenAddress,
		logger:      logger,
	}, nil
}

// ChainID returns ChainEVM to identify this adapter family.
func (s *EVMStaker) ChainID() chain.ChainType {
	return chain.ChainEVM
}

// HealthCheck verifies the adapter can reach the RPC node by fetching
// the latest block number.
func (s *EVMStaker) HealthCheck(ctx context.Context) error {
	if s.client == nil {
		return fmt.Errorf("evm: health check failed: no client")
	}
	_, err := s.client.BlockNumber(ctx)
	if err != nil {
		return fmt.Errorf("evm: health check failed: %w", err)
	}
	return nil
}

// GetTiers returns the hardcoded tier configuration matching the deployed
// staking contract. This avoids an RPC call for static data that only changes
// on a contract upgrade.
func (s *EVMStaker) GetTiers(_ context.Context) ([]chain.Tier, error) {
	return hardcodedTiers, nil
}

// Stake approves the staking contract to spend the requested token amount, then
// calls stake(amount, tier) on the contract. Returns a StakeReceipt with the
// transaction hash and the position ID parsed from the Staked event.
func (s *EVMStaker) Stake(ctx context.Context, req chain.StakeRequest) (chain.StakeReceipt, error) {
	if s.staking == nil || s.token == nil {
		return chain.StakeReceipt{}, ErrContractNotConnected
	}

	auth, err := s.transactOpts(ctx)
	if err != nil {
		return chain.StakeReceipt{}, fmt.Errorf("evm: build transact opts: %w", err)
	}

	// Step 1: approve staking contract to spend tokens.
	approveTx, err := s.token.Approve(auth, s.stakingAddr, req.Amount)
	if err != nil {
		return chain.StakeReceipt{}, fmt.Errorf("evm: approve failed: %w", err)
	}
	s.logger.Info().Str("tx", approveTx.Hash().Hex()).Msg("evm: waiting for approval tx")

	_, err = bind.WaitMined(ctx, s.client, approveTx)
	if err != nil {
		return chain.StakeReceipt{}, fmt.Errorf("evm: waiting for approval tx: %w", err)
	}

	// Step 2: stake.
	auth, err = s.transactOpts(ctx)
	if err != nil {
		return chain.StakeReceipt{}, fmt.Errorf("evm: build transact opts: %w", err)
	}

	stakeTx, err := s.staking.Stake(auth, req.Amount, tierToUint8(req.Tier))
	if err != nil {
		return chain.StakeReceipt{}, fmt.Errorf("evm: stake failed: %w", err)
	}

	receipt, err := bind.WaitMined(ctx, s.client, stakeTx)
	if err != nil {
		return chain.StakeReceipt{}, fmt.Errorf("evm: waiting for stake tx: %w", err)
	}

	// Parse the Staked event to get the positionID.
	var positionID string
	for _, log := range receipt.Logs {
		ev, parseErr := s.staking.ParseStaked(*log)
		if parseErr != nil {
			continue
		}
		positionID = ev.PositionId.String()
		break
	}

	s.logger.Info().
		Str("tx", stakeTx.Hash().Hex()).
		Str("positionID", positionID).
		Msg("evm: stake confirmed")

	return chain.StakeReceipt{
		PositionID: positionID,
		TxHash:     stakeTx.Hash().Hex(),
	}, nil
}

// Unstake calls unstake(positionId) on the contract and returns an UnstakeReceipt.
// AmountReturned, Rewards, and Penalty are parsed from the Unstaked event when present.
func (s *EVMStaker) Unstake(ctx context.Context, positionID string) (chain.UnstakeReceipt, error) {
	if s.staking == nil {
		return chain.UnstakeReceipt{}, ErrContractNotConnected
	}

	posID, ok := new(big.Int).SetString(positionID, 10)
	if !ok {
		return chain.UnstakeReceipt{}, fmt.Errorf("evm: invalid positionID %q", positionID)
	}

	auth, err := s.transactOpts(ctx)
	if err != nil {
		return chain.UnstakeReceipt{}, fmt.Errorf("evm: build transact opts: %w", err)
	}

	tx, err := s.staking.Unstake(auth, posID)
	if err != nil {
		return chain.UnstakeReceipt{}, fmt.Errorf("evm: unstake failed: %w", err)
	}

	receipt, err := bind.WaitMined(ctx, s.client, tx)
	if err != nil {
		return chain.UnstakeReceipt{}, fmt.Errorf("evm: waiting for unstake tx: %w", err)
	}

	result := chain.UnstakeReceipt{
		TxHash:         tx.Hash().Hex(),
		AmountReturned: new(big.Int),
		Rewards:        new(big.Int),
		Penalty:        new(big.Int),
	}

	for _, log := range receipt.Logs {
		ev, parseErr := s.staking.ParseUnstaked(*log)
		if parseErr != nil {
			continue
		}
		result.AmountReturned = ev.Amount
		result.Rewards = ev.Rewards
		result.Penalty = ev.Penalty
		break
	}

	s.logger.Info().Str("tx", tx.Hash().Hex()).Msg("evm: unstake confirmed")
	return result, nil
}

// ClaimRewards calls claimRewards(positionId) on the contract.
// RewardsClaimed is parsed from the RewardsClaimed event when present.
func (s *EVMStaker) ClaimRewards(ctx context.Context, positionID string) (chain.ClaimReceipt, error) {
	if s.staking == nil {
		return chain.ClaimReceipt{}, ErrContractNotConnected
	}

	posID, ok := new(big.Int).SetString(positionID, 10)
	if !ok {
		return chain.ClaimReceipt{}, fmt.Errorf("evm: invalid positionID %q", positionID)
	}

	auth, err := s.transactOpts(ctx)
	if err != nil {
		return chain.ClaimReceipt{}, fmt.Errorf("evm: build transact opts: %w", err)
	}

	tx, err := s.staking.ClaimRewards(auth, posID)
	if err != nil {
		return chain.ClaimReceipt{}, fmt.Errorf("evm: claimRewards failed: %w", err)
	}

	receipt, err := bind.WaitMined(ctx, s.client, tx)
	if err != nil {
		return chain.ClaimReceipt{}, fmt.Errorf("evm: waiting for claimRewards tx: %w", err)
	}

	result := chain.ClaimReceipt{
		TxHash:         tx.Hash().Hex(),
		RewardsClaimed: new(big.Int),
	}

	for _, log := range receipt.Logs {
		ev, parseErr := s.staking.ParseRewardsClaimed(*log)
		if parseErr != nil {
			continue
		}
		result.RewardsClaimed = ev.Amount
		break
	}

	s.logger.Info().Str("tx", tx.Hash().Hex()).Msg("evm: claimRewards confirmed")
	return result, nil
}

// GetPosition calls getPosition(positionId) on the contract and converts the
// on-chain struct to a chain.StakePosition.
func (s *EVMStaker) GetPosition(ctx context.Context, positionID string) (chain.StakePosition, error) {
	if s.staking == nil {
		return chain.StakePosition{}, ErrContractNotConnected
	}

	posID, ok := new(big.Int).SetString(positionID, 10)
	if !ok {
		return chain.StakePosition{}, fmt.Errorf("evm: invalid positionID %q", positionID)
	}

	pos, err := s.staking.GetPosition(&bind.CallOpts{Context: ctx}, posID)
	if err != nil {
		return chain.StakePosition{}, fmt.Errorf("evm: getPosition failed: %w", err)
	}

	status := chain.StatusActive
	if !pos.Active {
		status = chain.StatusUnstaked
	}

	stakedAt := time.Unix(pos.StakedAt.Int64(), 0)
	lockUntil := time.Unix(pos.LockUntil.Int64(), 0)

	return chain.StakePosition{
		ID:             positionID,
		Chain:          chain.ChainEVM,
		Wallet:         pos.Owner.Hex(),
		Amount:         pos.Amount,
		Tier:           uint8ToTier(pos.Tier),
		Status:         status,
		StakedAt:       stakedAt,
		LockUntil:      lockUntil,
		AccruedRewards: new(big.Int),
	}, nil
}

// ListPositions always returns ErrUseIndexedDB. Position listing is delegated
// to the off-chain indexer which maintains a queryable database of events.
func (s *EVMStaker) ListPositions(_ context.Context, _ string) ([]chain.StakePosition, error) {
	return nil, ErrUseIndexedDB
}

// transactOpts creates a bind.TransactOpts from the signer's private key and chain ID.
func (s *EVMStaker) transactOpts(ctx context.Context) (*bind.TransactOpts, error) {
	auth, err := bind.NewKeyedTransactorWithChainID(s.signer.PrivateKey(), s.signer.ChainID())
	if err != nil {
		return nil, fmt.Errorf("evm: create transactor: %w", err)
	}
	auth.Context = ctx
	return auth, nil
}

// tierToUint8 converts a domain TierType to the uint8 used by the contract.
// Bronze=0, Silver=1, Gold=2. Unknown tiers default to 0 (Bronze).
func tierToUint8(t chain.TierType) uint8 {
	switch t {
	case chain.TierSilver:
		return 1
	case chain.TierGold:
		return 2
	default:
		return 0
	}
}

// uint8ToTier converts the contract's uint8 tier enum back to a domain TierType.
func uint8ToTier(t uint8) chain.TierType {
	switch t {
	case 1:
		return chain.TierSilver
	case 2:
		return chain.TierGold
	default:
		return chain.TierBronze
	}
}

// compile-time interface assertion — this line will not compile if EVMStaker
// ever drifts out of sync with the ChainStaker interface.
var _ chain.ChainStaker = (*EVMStaker)(nil)
