// Package evm provides a ChainStaker adapter for EVM-compatible chains.
// Contract bindings are expected to be generated by abigen; until they are
// wired the mutation methods return a clearly documented sentinel error so
// callers can distinguish "not yet integrated" from a real RPC failure.
package evm

import (
	"context"
	"errors"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/jhionan/multichain-staking/internal/chain"
	"github.com/jhionan/multichain-staking/internal/signer"
	"github.com/rs/zerolog"
)

// ErrContractNotConnected is returned by transaction methods until the abigen
// bindings are integrated and wired into the adapter.
var ErrContractNotConnected = errors.New("evm: not connected to contract — abigen bindings not yet integrated")

// ErrUseIndexedDB is returned by ListPositions because position listing is
// handled by the off-chain indexer, not by direct contract reads.
var ErrUseIndexedDB = errors.New("evm: use indexed DB for listing positions")

// hardcodedTiers mirrors the on-chain tier configuration.
// Values must be kept in sync with the deployed contract constants.
var hardcodedTiers = []chain.Tier{
	{
		Type:     chain.TierBronze,
		LockDays: 30,
		APRBps:   500,
		MinStake: big.NewInt(0), // placeholder until contract ABI is available
	},
	{
		Type:     chain.TierSilver,
		LockDays: 60,
		APRBps:   1000,
		MinStake: big.NewInt(0),
	},
	{
		Type:     chain.TierGold,
		LockDays: 90,
		APRBps:   1800,
		MinStake: big.NewInt(0),
	},
}

// EVMStaker implements chain.ChainStaker for EVM-compatible chains.
type EVMStaker struct {
	client *ethclient.Client
	signer *signer.EVMSigner
	logger zerolog.Logger
}

// NewEVMStaker creates an EVMStaker.
// client and logger are required; signer may be nil for read-only operation.
func NewEVMStaker(client *ethclient.Client, sgn *signer.EVMSigner, logger zerolog.Logger) (*EVMStaker, error) {
	if client == nil {
		return nil, fmt.Errorf("evm: ethclient must not be nil")
	}
	return &EVMStaker{
		client: client,
		signer: sgn,
		logger: logger,
	}, nil
}

// ChainID returns ChainEVM to identify this adapter family.
func (s *EVMStaker) ChainID() chain.ChainType {
	return chain.ChainEVM
}

// HealthCheck verifies the adapter can reach the RPC node by fetching
// the latest block number.
func (s *EVMStaker) HealthCheck(ctx context.Context) error {
	_, err := s.client.BlockNumber(ctx)
	if err != nil {
		return fmt.Errorf("evm: health check failed: %w", err)
	}
	return nil
}

// GetTiers returns the hardcoded tier configuration matching the deployed
// staking contract. This avoids an RPC call for static data that only changes
// on a contract upgrade.
func (s *EVMStaker) GetTiers(_ context.Context) ([]chain.Tier, error) {
	return hardcodedTiers, nil
}

// Stake is a placeholder. It will be implemented once the abigen contract
// bindings are generated and imported.
func (s *EVMStaker) Stake(_ context.Context, _ chain.StakeRequest) (chain.StakeReceipt, error) {
	return chain.StakeReceipt{}, ErrContractNotConnected
}

// Unstake is a placeholder pending abigen integration.
func (s *EVMStaker) Unstake(_ context.Context, _ string) (chain.UnstakeReceipt, error) {
	return chain.UnstakeReceipt{}, ErrContractNotConnected
}

// ClaimRewards is a placeholder pending abigen integration.
func (s *EVMStaker) ClaimRewards(_ context.Context, _ string) (chain.ClaimReceipt, error) {
	return chain.ClaimReceipt{}, ErrContractNotConnected
}

// GetPosition is a placeholder pending abigen integration.
func (s *EVMStaker) GetPosition(_ context.Context, _ string) (chain.StakePosition, error) {
	return chain.StakePosition{}, ErrContractNotConnected
}

// ListPositions always returns ErrUseIndexedDB. Position listing is delegated
// to the off-chain indexer which maintains a queryable database of events.
func (s *EVMStaker) ListPositions(_ context.Context, _ string) ([]chain.StakePosition, error) {
	return nil, ErrUseIndexedDB
}

// compile-time interface assertion — this line will not compile if EVMStaker
// ever drifts out of sync with the ChainStaker interface.
var _ chain.ChainStaker = (*EVMStaker)(nil)
