// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestAuditLog = `-- name: GetLatestAuditLog :one
SELECT id, action, actor, chain_id, details, prev_hash, hash, created_at FROM audit_log ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestAuditLog(ctx context.Context) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getLatestAuditLog)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.Actor,
		&i.ChainID,
		&i.Details,
		&i.PrevHash,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (action, actor, chain_id, details, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, action, actor, chain_id, details, prev_hash, hash, created_at
`

type InsertAuditLogParams struct {
	Action   string      `json:"action"`
	Actor    string      `json:"actor"`
	ChainID  pgtype.Text `json:"chain_id"`
	Details  []byte      `json:"details"`
	PrevHash pgtype.Text `json:"prev_hash"`
	Hash     string      `json:"hash"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.Action,
		arg.Actor,
		arg.ChainID,
		arg.Details,
		arg.PrevHash,
		arg.Hash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.Actor,
		&i.ChainID,
		&i.Details,
		&i.PrevHash,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, action, actor, chain_id, details, prev_hash, hash, created_at FROM audit_log ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Actor,
			&i.ChainID,
			&i.Details,
			&i.PrevHash,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
