// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: block_cursors.sql

package db

import (
	"context"
)

const getBlockCursor = `-- name: GetBlockCursor :one
SELECT chain_id, last_block, updated_at FROM block_cursors WHERE chain_id = $1
`

func (q *Queries) GetBlockCursor(ctx context.Context, chainID string) (BlockCursor, error) {
	row := q.db.QueryRow(ctx, getBlockCursor, chainID)
	var i BlockCursor
	err := row.Scan(&i.ChainID, &i.LastBlock, &i.UpdatedAt)
	return i, err
}

const resetAllBlockCursors = `-- name: ResetAllBlockCursors :exec
TRUNCATE TABLE block_cursors
`

func (q *Queries) ResetAllBlockCursors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAllBlockCursors)
	return err
}

const resetBlockCursor = `-- name: ResetBlockCursor :exec
DELETE FROM block_cursors WHERE chain_id = $1
`

func (q *Queries) ResetBlockCursor(ctx context.Context, chainID string) error {
	_, err := q.db.Exec(ctx, resetBlockCursor, chainID)
	return err
}

const upsertBlockCursor = `-- name: UpsertBlockCursor :exec
INSERT INTO block_cursors (chain_id, last_block, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (chain_id) DO UPDATE SET
    last_block = EXCLUDED.last_block,
    updated_at = NOW()
`

type UpsertBlockCursorParams struct {
	ChainID   string `json:"chain_id"`
	LastBlock int64  `json:"last_block"`
}

func (q *Queries) UpsertBlockCursor(ctx context.Context, arg UpsertBlockCursorParams) error {
	_, err := q.db.Exec(ctx, upsertBlockCursor, arg.ChainID, arg.LastBlock)
	return err
}
