// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chain_events.sql

package db

import (
	"context"
)

const getEventsByBlock = `-- name: GetEventsByBlock :many
SELECT id, chain_id, event_type, tx_hash, log_index, block_number, raw_data, indexed_at FROM chain_events WHERE chain_id = $1 AND block_number = $2
`

type GetEventsByBlockParams struct {
	ChainID     string `json:"chain_id"`
	BlockNumber int64  `json:"block_number"`
}

func (q *Queries) GetEventsByBlock(ctx context.Context, arg GetEventsByBlockParams) ([]ChainEvent, error) {
	rows, err := q.db.Query(ctx, getEventsByBlock, arg.ChainID, arg.BlockNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChainEvent
	for rows.Next() {
		var i ChainEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.EventType,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.RawData,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByTxHash = `-- name: GetEventsByTxHash :many
SELECT id, chain_id, event_type, tx_hash, log_index, block_number, raw_data, indexed_at FROM chain_events WHERE tx_hash = $1
`

func (q *Queries) GetEventsByTxHash(ctx context.Context, txHash string) ([]ChainEvent, error) {
	rows, err := q.db.Query(ctx, getEventsByTxHash, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChainEvent
	for rows.Next() {
		var i ChainEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.EventType,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.RawData,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChainEvent = `-- name: InsertChainEvent :one
INSERT INTO chain_events (chain_id, event_type, tx_hash, log_index, block_number, raw_data)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tx_hash, log_index) DO NOTHING
RETURNING id, chain_id, event_type, tx_hash, log_index, block_number, raw_data, indexed_at
`

type InsertChainEventParams struct {
	ChainID     string `json:"chain_id"`
	EventType   string `json:"event_type"`
	TxHash      string `json:"tx_hash"`
	LogIndex    int32  `json:"log_index"`
	BlockNumber int64  `json:"block_number"`
	RawData     []byte `json:"raw_data"`
}

func (q *Queries) InsertChainEvent(ctx context.Context, arg InsertChainEventParams) (ChainEvent, error) {
	row := q.db.QueryRow(ctx, insertChainEvent,
		arg.ChainID,
		arg.EventType,
		arg.TxHash,
		arg.LogIndex,
		arg.BlockNumber,
		arg.RawData,
	)
	var i ChainEvent
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.EventType,
		&i.TxHash,
		&i.LogIndex,
		&i.BlockNumber,
		&i.RawData,
		&i.IndexedAt,
	)
	return i, err
}

const truncateChainEvents = `-- name: TruncateChainEvents :exec
TRUNCATE TABLE chain_events
`

func (q *Queries) TruncateChainEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateChainEvents)
	return err
}
