// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	Action    string             `json:"action"`
	Actor     string             `json:"actor"`
	ChainID   pgtype.Text        `json:"chain_id"`
	Details   []byte             `json:"details"`
	PrevHash  pgtype.Text        `json:"prev_hash"`
	Hash      string             `json:"hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BlockCursor struct {
	ChainID   string             `json:"chain_id"`
	LastBlock int64              `json:"last_block"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ChainEvent struct {
	ID          pgtype.UUID        `json:"id"`
	ChainID     string             `json:"chain_id"`
	EventType   string             `json:"event_type"`
	TxHash      string             `json:"tx_hash"`
	LogIndex    int32              `json:"log_index"`
	BlockNumber int64              `json:"block_number"`
	RawData     []byte             `json:"raw_data"`
	IndexedAt   pgtype.Timestamptz `json:"indexed_at"`
}

type Position struct {
	ID        pgtype.UUID        `json:"id"`
	ChainID   string             `json:"chain_id"`
	Wallet    string             `json:"wallet"`
	Amount    pgtype.Numeric     `json:"amount"`
	Tier      string             `json:"tier"`
	StakedAt  pgtype.Timestamptz `json:"staked_at"`
	LockUntil pgtype.Timestamptz `json:"lock_until"`
	Status    string             `json:"status"`
	TxHash    string             `json:"tx_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Reward struct {
	ID               pgtype.UUID        `json:"id"`
	PositionID       pgtype.UUID        `json:"position_id"`
	AccruedAmount    pgtype.Numeric     `json:"accrued_amount"`
	LastCalculatedAt pgtype.Timestamptz `json:"last_calculated_at"`
}
