// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPosition = `-- name: GetPosition :one
SELECT id, chain_id, wallet, amount, tier, staked_at, lock_until, status, tx_hash, created_at, updated_at FROM positions WHERE id = $1
`

func (q *Queries) GetPosition(ctx context.Context, id pgtype.UUID) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Wallet,
		&i.Amount,
		&i.Tier,
		&i.StakedAt,
		&i.LockUntil,
		&i.Status,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPosition = `-- name: InsertPosition :one
INSERT INTO positions (chain_id, wallet, amount, tier, staked_at, lock_until, status, tx_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chain_id, wallet, amount, tier, staked_at, lock_until, status, tx_hash, created_at, updated_at
`

type InsertPositionParams struct {
	ChainID   string             `json:"chain_id"`
	Wallet    string             `json:"wallet"`
	Amount    pgtype.Numeric     `json:"amount"`
	Tier      string             `json:"tier"`
	StakedAt  pgtype.Timestamptz `json:"staked_at"`
	LockUntil pgtype.Timestamptz `json:"lock_until"`
	Status    string             `json:"status"`
	TxHash    string             `json:"tx_hash"`
}

func (q *Queries) InsertPosition(ctx context.Context, arg InsertPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, insertPosition,
		arg.ChainID,
		arg.Wallet,
		arg.Amount,
		arg.Tier,
		arg.StakedAt,
		arg.LockUntil,
		arg.Status,
		arg.TxHash,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Wallet,
		&i.Amount,
		&i.Tier,
		&i.StakedAt,
		&i.LockUntil,
		&i.Status,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPositionsByChain = `-- name: ListPositionsByChain :many
SELECT id, chain_id, wallet, amount, tier, staked_at, lock_until, status, tx_hash, created_at, updated_at FROM positions WHERE chain_id = $1 ORDER BY staked_at DESC
`

func (q *Queries) ListPositionsByChain(ctx context.Context, chainID string) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByChain, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.Wallet,
			&i.Amount,
			&i.Tier,
			&i.StakedAt,
			&i.LockUntil,
			&i.Status,
			&i.TxHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByWallet = `-- name: ListPositionsByWallet :many
SELECT id, chain_id, wallet, amount, tier, staked_at, lock_until, status, tx_hash, created_at, updated_at FROM positions WHERE chain_id = $1 AND wallet = $2 ORDER BY staked_at DESC
`

type ListPositionsByWalletParams struct {
	ChainID string `json:"chain_id"`
	Wallet  string `json:"wallet"`
}

func (q *Queries) ListPositionsByWallet(ctx context.Context, arg ListPositionsByWalletParams) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByWallet, arg.ChainID, arg.Wallet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.Wallet,
			&i.Amount,
			&i.Tier,
			&i.StakedAt,
			&i.LockUntil,
			&i.Status,
			&i.TxHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncatePositions = `-- name: TruncatePositions :exec
TRUNCATE TABLE positions CASCADE
`

func (q *Queries) TruncatePositions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncatePositions)
	return err
}

const updatePositionStatus = `-- name: UpdatePositionStatus :exec
UPDATE positions SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdatePositionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdatePositionStatus(ctx context.Context, arg UpdatePositionStatusParams) error {
	_, err := q.db.Exec(ctx, updatePositionStatus, arg.ID, arg.Status)
	return err
}

const upsertPosition = `-- name: UpsertPosition :one
INSERT INTO positions (chain_id, wallet, amount, tier, staked_at, lock_until, status, tx_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    updated_at = NOW()
RETURNING id, chain_id, wallet, amount, tier, staked_at, lock_until, status, tx_hash, created_at, updated_at
`

type UpsertPositionParams struct {
	ChainID   string             `json:"chain_id"`
	Wallet    string             `json:"wallet"`
	Amount    pgtype.Numeric     `json:"amount"`
	Tier      string             `json:"tier"`
	StakedAt  pgtype.Timestamptz `json:"staked_at"`
	LockUntil pgtype.Timestamptz `json:"lock_until"`
	Status    string             `json:"status"`
	TxHash    string             `json:"tx_hash"`
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, upsertPosition,
		arg.ChainID,
		arg.Wallet,
		arg.Amount,
		arg.Tier,
		arg.StakedAt,
		arg.LockUntil,
		arg.Status,
		arg.TxHash,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.Wallet,
		&i.Amount,
		&i.Tier,
		&i.StakedAt,
		&i.LockUntil,
		&i.Status,
		&i.TxHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
