// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetBlockCursor(ctx context.Context, chainID string) (BlockCursor, error)
	GetEventsByBlock(ctx context.Context, arg GetEventsByBlockParams) ([]ChainEvent, error)
	GetEventsByTxHash(ctx context.Context, txHash string) ([]ChainEvent, error)
	GetLatestAuditLog(ctx context.Context) (AuditLog, error)
	GetPosition(ctx context.Context, id pgtype.UUID) (Position, error)
	GetRewardByPosition(ctx context.Context, positionID pgtype.UUID) (Reward, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertChainEvent(ctx context.Context, arg InsertChainEventParams) (ChainEvent, error)
	InsertPosition(ctx context.Context, arg InsertPositionParams) (Position, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListPositionsByChain(ctx context.Context, chainID string) ([]Position, error)
	ListPositionsByWallet(ctx context.Context, arg ListPositionsByWalletParams) ([]Position, error)
	ResetAllBlockCursors(ctx context.Context) error
	ResetBlockCursor(ctx context.Context, chainID string) error
	TruncateChainEvents(ctx context.Context) error
	TruncatePositions(ctx context.Context) error
	TruncateRewards(ctx context.Context) error
	UpdatePositionStatus(ctx context.Context, arg UpdatePositionStatusParams) error
	UpsertBlockCursor(ctx context.Context, arg UpsertBlockCursorParams) error
	UpsertPosition(ctx context.Context, arg UpsertPositionParams) (Position, error)
	UpsertReward(ctx context.Context, arg UpsertRewardParams) (Reward, error)
}

var _ Querier = (*Queries)(nil)
