// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rewards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRewardByPosition = `-- name: GetRewardByPosition :one
SELECT id, position_id, accrued_amount, last_calculated_at FROM rewards WHERE position_id = $1
`

func (q *Queries) GetRewardByPosition(ctx context.Context, positionID pgtype.UUID) (Reward, error) {
	row := q.db.QueryRow(ctx, getRewardByPosition, positionID)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.AccruedAmount,
		&i.LastCalculatedAt,
	)
	return i, err
}

const truncateRewards = `-- name: TruncateRewards :exec
TRUNCATE TABLE rewards
`

func (q *Queries) TruncateRewards(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateRewards)
	return err
}

const upsertReward = `-- name: UpsertReward :one
INSERT INTO rewards (position_id, accrued_amount, last_calculated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (position_id) DO UPDATE SET
    accrued_amount = EXCLUDED.accrued_amount,
    last_calculated_at = NOW()
RETURNING id, position_id, accrued_amount, last_calculated_at
`

type UpsertRewardParams struct {
	PositionID    pgtype.UUID    `json:"position_id"`
	AccruedAmount pgtype.Numeric `json:"accrued_amount"`
}

func (q *Queries) UpsertReward(ctx context.Context, arg UpsertRewardParams) (Reward, error) {
	row := q.db.QueryRow(ctx, upsertReward, arg.PositionID, arg.AccruedAmount)
	var i Reward
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.AccruedAmount,
		&i.LastCalculatedAt,
	)
	return i, err
}
